version: '3.8'

services:
    api-server:
        user: root
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/usr/src/app'
            - /usr/src/app/node_modules
        ports:
            - 3001:3000
        environment:
            - CHOKIDAR_USEPOLLING=true

    api-server-prod:
        build:
            context: .
            dockerfile: Dockerfile.Prod
        ports:
            - '3000:80'